/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pviyaouvohpwgdonzzyk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2aXlhb3V2b2hwd2dkb256enlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMjk5NjAsImV4cCI6MjA3ODcwNTk2MH0.f_ffTnQlgITi8JuTyLY-Mm-KOT7-YOQcrfgL3eUxMe8"